apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: client-hpa
spec:
  maxReplicas: 2 # define max replica count
  minReplicas: 2  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: angular-deployment
  targetCPUUtilizationPercentage: 90 # target CPU utilization